apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
        - name: ai-api
          image: sagamarketplaceacr.azurecr.io/ai-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"

            - name: Gemini__ApiKey
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: Gemini__ApiKey

            - name: Gemini__Model
              valueFrom:
                configMapKeyRef:
                  name: saga-config
                  key: Gemini__Model

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"