apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

    spec:
      containers:
        - name: order-api
          image: sagamarketplaceacr.azurecr.io/order-api:day18

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"

            - name: RabbitMq__HostName
              valueFrom:
                configMapKeyRef:
                  name: saga-config
                  key: RabbitMq__HostName

            - name: RabbitMq__UserName
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: RabbitMq__UserName

            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: RabbitMq__Password

            - name: RabbitMq__VirtualHost
              value: "/"

            - name: ConnectionStrings__OrderDb
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: OrderDbConnectionString