apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: Postgres__UserName

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: Postgres__Password

            - name: POSTGRES_DB
              value: order_db