apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api

    spec:
      containers:
        - name: catalog-api
          image: sagamarketplaceacr.azurecr.io/catalog-api:latest
          env:
            - name: ConnectionStrings__CatalogDb
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: CatalogDbConnectionString

            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: ServiceBusConnectionString

            - name: ServiceBus__RecommendationTopicName
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: RecommendationTopicName

            - name: CosmosDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: CosmosDbConnectionString

            - name: CosmosDb__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: CosmosDbDatabaseName

            - name: CosmosDb__ContainerName
              valueFrom:
                secretKeyRef:
                  name: saga-secret
                  key: CosmosDbContainerName
          ports:
            - containerPort: 8080